---
- name: Set GNOME settings with dconf
  become: false  # Run as unprivileged user, not as root
  block:
    - name: Show weekday in desktop clock
      community.general.dconf:
        key: "/org/gnome/desktop/interface/clock-show-weekday"
        value: "true"
        state: present

    - name: Enable dark mode
      community.general.dconf:
        key: "/org/gnome/desktop/interface/color-scheme"
        value: "'prefer-dark'"
        state: present

    - name: Set text scaling to 1.5x (150%)
      community.general.dconf:
        key: "/org/gnome/desktop/interface/text-scaling-factor"
        value: "1.5"
        state: present

    - name: Disable lock screen notifications
      community.general.dconf:
        key: "/org/gnome/desktop/notifications/show-in-lock-screen"
        value: "false"
        state: present

    - name: Remove old files after 7 days
      community.general.dconf:
        key: "/org/gnome/desktop/privacy/old-files-age"
        value: "uint32 7"
        state: present

    - name: Do not remember recent files
      community.general.dconf:
        key: "/org/gnome/desktop/privacy/remember-recent-files"
        value: "false"
        state: present

    - name: Automatically remove temp files
      community.general.dconf:
        key: "/org/gnome/desktop/privacy/remove-old-temp-files"
        value: "true"
        state: present

    - name: Automatically empty trash
      community.general.dconf:
        key: "/org/gnome/desktop/privacy/remove-old-trash-files"
        value: "true"
        state: present

    - name: Enable Edge Tiling (dragging window to side of screen to resize)
      community.general.dconf:
        key: "/org/gnome/mutter/edge-tiling"
        value: "true"
        state: present
...
