---
- name: Install dnf5-plugin-automatic
  become: true
  ansible.builtin.dnf:
    name: dnf5-plugin-automatic
    state: present

- name: Configure update installation
  become: true
  community.general.ini_file:
    path: /etc/dnf/automatic.conf
    section: 'commands'
    option: 'apply_updates'
    value: 'yes'
    mode: '0644'
    owner: root
    group: root

- name: Enable dnf5-automatic.timer
  become: true
  ansible.builtin.systemd_service:
    name: dnf5-automatic.timer
    state: started
    enabled: true
...
